[project]
name = "data-juicer-agent"
version = "0.1.0"
description = "A data processing agent with data juicer"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agentscope>=1.0.5",
    "faiss-cpu>=1.12.0",
    "langchain-community",
    "py-data-juicer>=1.4.2",
]
