name: Run test_structured_model.py

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          # ✅ Show actual directory structure
          echo "Current directory: $(pwd)"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pytest pytest-asyncio  # ✅ Add pytest-asyncio for async tests
          pip install agentscope dashscope  # ✅ Add missing dependencies
          pip install -e .  # Install local package in development mode

      - name: Run game_structured_model.py
        run: |
          # ✅ Ensure correct working directory
          cd tests
          python3 -m pytest game_structured_model.py -v