name: Run test_units.py

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          # ✅ Show actual directory structure
          echo "Current directory: $(pwd)"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          cd games/game_werewolves
          pip install pytest pytest-asyncio
          pip install -r requirements.txt

      - name: Run game_utils.py
        env:
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
        run: |
          # ✅ Ensure correct working directory
          cd test  # Or `cd tests` if directory name differs
          python3 -m pytest game_utils.py -v